/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import javax.swing.JFrame;

/**
 *
 * @author Julia
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        this.setLocationRelativeTo(null); // Admin window is shown in the center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Admin_Ad = new javax.swing.JLabel();
        jLabel_hideWindow_Ad = new javax.swing.JLabel();
        jLabel_closeWindow_Ad = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_ChooseAccount_Ad = new javax.swing.JLabel();
        jComboBox_AccountSelection_Ad = new javax.swing.JComboBox<>();
        jCheckBox_AllowEmail_Ad = new javax.swing.JCheckBox();
        jLabel_InformationAboutAccount_Ad = new javax.swing.JLabel();
        jLabel_Firstname_Ad = new javax.swing.JLabel();
        jButton_ModifyAccount_Ad = new javax.swing.JButton();
        jButton_deleteAccount_Ad = new javax.swing.JButton();
        jTextField_Firstname_Ad = new javax.swing.JTextField();
        jTextField_Lastname_Ad = new javax.swing.JTextField();
        jTextField_Username_Ad = new javax.swing.JTextField();
        jTextField_Email_Ad = new javax.swing.JTextField();
        jTextField_Password_Ad = new javax.swing.JTextField();
        jLabel_Lastname_Ad = new javax.swing.JLabel();
        jLabel_Username_Ad = new javax.swing.JLabel();
        jLabel_Email_Ad = new javax.swing.JLabel();
        jLabel_Password_Ad = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton_cancel_Ad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(137, 196, 244));

        jLabel_Admin_Ad.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Admin_Ad.setText("Admin Menu");

        jLabel_hideWindow_Ad.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_hideWindow_Ad.setText("-");
        jLabel_hideWindow_Ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_hideWindow_Ad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_hideWindow_AdMouseClicked(evt);
            }
        });

        jLabel_closeWindow_Ad.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_closeWindow_Ad.setText("X");
        jLabel_closeWindow_Ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_closeWindow_Ad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeWindow_AdMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Admin_Ad)
                .addGap(241, 241, 241)
                .addComponent(jLabel_hideWindow_Ad)
                .addGap(18, 18, 18)
                .addComponent(jLabel_closeWindow_Ad)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Admin_Ad)
                    .addComponent(jLabel_hideWindow_Ad)
                    .addComponent(jLabel_closeWindow_Ad))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(231, 246, 255));

        jLabel_ChooseAccount_Ad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_ChooseAccount_Ad.setText("Choose an account:");

        jComboBox_AccountSelection_Ad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account 1", "Account  2", "Account 3", "Account 4" }));
        jComboBox_AccountSelection_Ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox_AccountSelection_Ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_AccountSelection_AdActionPerformed(evt);
            }
        });

        jCheckBox_AllowEmail_Ad.setText("Receive information about changes via email");
        jCheckBox_AllowEmail_Ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox_AllowEmail_Ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_AllowEmail_AdActionPerformed(evt);
            }
        });

        jLabel_InformationAboutAccount_Ad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_InformationAboutAccount_Ad.setText("Information about the choosen account:");

        jLabel_Firstname_Ad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Firstname_Ad.setText("Firstname:");

        jButton_ModifyAccount_Ad.setText("Modify account information");
        jButton_ModifyAccount_Ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ModifyAccount_Ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModifyAccount_AdActionPerformed(evt);
            }
        });

        jButton_deleteAccount_Ad.setText("delete account");
        jButton_deleteAccount_Ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_deleteAccount_Ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteAccount_AdActionPerformed(evt);
            }
        });

        jTextField_Firstname_Ad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel_Lastname_Ad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Lastname_Ad.setText("Lastname:");

        jLabel_Username_Ad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Username_Ad.setText("Username:");

        jLabel_Email_Ad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Email_Ad.setText("Email:");

        jLabel_Password_Ad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Password_Ad.setText("Password:");

        jButton1.setText("show TimeScheduler");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_deleteAccount_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_ChooseAccount_Ad)
                                    .addComponent(jLabel_InformationAboutAccount_Ad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Lastname_Ad)
                                    .addComponent(jLabel_Firstname_Ad)
                                    .addComponent(jLabel_Username_Ad)
                                    .addComponent(jLabel_Email_Ad)
                                    .addComponent(jLabel_Password_Ad))
                                .addGap(75, 75, 75)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Password_Ad)
                            .addComponent(jTextField_Email_Ad)
                            .addComponent(jTextField_Username_Ad)
                            .addComponent(jTextField_Lastname_Ad)
                            .addComponent(jComboBox_AccountSelection_Ad, 0, 211, Short.MAX_VALUE)
                            .addComponent(jTextField_Firstname_Ad))))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ModifyAccount_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox_AllowEmail_Ad)
                        .addGap(255, 255, 255))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ChooseAccount_Ad)
                    .addComponent(jComboBox_AccountSelection_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_InformationAboutAccount_Ad)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Firstname_Ad)
                    .addComponent(jTextField_Firstname_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Lastname_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Lastname_Ad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Username_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Username_Ad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Email_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Email_Ad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Password_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Password_Ad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ModifyAccount_Ad)
                    .addComponent(jButton_deleteAccount_Ad)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_AllowEmail_Ad)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(137, 196, 244));

        jButton_cancel_Ad.setText("cancel");
        jButton_cancel_Ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cancel_Ad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_cancel_AdMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_cancel_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jButton_cancel_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_AllowEmail_AdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_AllowEmail_AdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_AllowEmail_AdActionPerformed

    private void jLabel_closeWindow_AdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeWindow_AdMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeWindow_AdMouseClicked

    private void jLabel_hideWindow_AdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_hideWindow_AdMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);  // minimize the Admin screen
    }//GEN-LAST:event_jLabel_hideWindow_AdMouseClicked

    private void jButton_cancel_AdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_cancel_AdMouseClicked
        // TODO add your handling code here:
        System.exit(0);  //close Admin window
    }//GEN-LAST:event_jButton_cancel_AdMouseClicked

    private void jComboBox_AccountSelection_AdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_AccountSelection_AdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_AccountSelection_AdActionPerformed

    private void jButton_deleteAccount_AdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteAccount_AdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_deleteAccount_AdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Calendar().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_ModifyAccount_AdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModifyAccount_AdActionPerformed
        // TODO add your handling code here:
        new Account().setVisible(true);
    }//GEN-LAST:event_jButton_ModifyAccount_AdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_ModifyAccount_Ad;
    private javax.swing.JButton jButton_cancel_Ad;
    private javax.swing.JButton jButton_deleteAccount_Ad;
    private javax.swing.JCheckBox jCheckBox_AllowEmail_Ad;
    private javax.swing.JComboBox<String> jComboBox_AccountSelection_Ad;
    private javax.swing.JLabel jLabel_Admin_Ad;
    private javax.swing.JLabel jLabel_ChooseAccount_Ad;
    private javax.swing.JLabel jLabel_Email_Ad;
    private javax.swing.JLabel jLabel_Firstname_Ad;
    private javax.swing.JLabel jLabel_InformationAboutAccount_Ad;
    private javax.swing.JLabel jLabel_Lastname_Ad;
    private javax.swing.JLabel jLabel_Password_Ad;
    private javax.swing.JLabel jLabel_Username_Ad;
    private javax.swing.JLabel jLabel_closeWindow_Ad;
    private javax.swing.JLabel jLabel_hideWindow_Ad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_Email_Ad;
    private javax.swing.JTextField jTextField_Firstname_Ad;
    private javax.swing.JTextField jTextField_Lastname_Ad;
    private javax.swing.JTextField jTextField_Password_Ad;
    private javax.swing.JTextField jTextField_Username_Ad;
    // End of variables declaration//GEN-END:variables
}
