
import java.awt.*;
import java.awt.event.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.*;
import javax.swing.table.*;


/**
 *
 * @author arseny
 */
public class SwingCalendar extends javax.swing.JFrame {
 DefaultTableModel model;
 Calendar calendar = new GregorianCalendar();
 JLabel month_label;
    
    
    public SwingCalendar() { //create new form calender
        initComponents();
        
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.setTitle("Swing Calendar"); //titel
    this.setSize(300,200);
    this.setLayout(new BorderLayout());
    this.setVisible(true);//gives standard characteristics to window and shows it on the desktop
    
    month_label = new JLabel();//creat month field
    month_label.setHorizontalAlignment(SwingConstants.CENTER);
    
    
    JPanel panel = new JPanel();
    panel.setLayout(new BorderLayout());
    panel.add(month_label,BorderLayout.CENTER);
    
    //create columns for week days
    String [] columns = {"Sun","Mon","Tue","Wed","Thu","Fri","Sat"};
    model = new DefaultTableModel(null,columns);
    JTable table = new JTable(model);
    JScrollPane pane = new JScrollPane(table);
 
    this.add(panel,BorderLayout.NORTH);
    this.add(pane,BorderLayout.CENTER);
    
    //create buttons
    JButton arrow_1 = new JButton("<-");
   
    //add action to arrow_1
    arrow_1.addActionListener(new ActionListener()
    {
        public void actionPerformed(ActionEvent ae) {
            calendar.add(Calendar.MONTH,-1);
            update_month();
        }
    });
    
    JButton arrow_2 = new JButton("->");
    
    //add action to arrow_2
    arrow_2.addActionListener(new ActionListener()
    {
        public void actionPerformed(ActionEvent ae) {
            calendar.add(Calendar.MONTH,+1);
            update_month();
        }
    });
    
    panel.add(arrow_1,BorderLayout.WEST);
    panel.add(arrow_2,BorderLayout.EAST);
    
    this.update_month();
    
    }
    void update_month()
    {
    calendar.set(GregorianCalendar.DAY_OF_MONTH, 1);
    String month = calendar.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.GERMAN);
    int year = calendar.get(Calendar.YEAR);
    month_label.setText(month + " " + year);
    
    int start_day = calendar.get(Calendar.DAY_OF_WEEK);
    int number_of_days = calendar.getActualMaximum(Calendar.DAY_OF_MONTH);
    int weeks = calendar.getActualMaximum(Calendar.WEEK_OF_MONTH);
    
    model.setRowCount(0);//Sets the number of rows in the model.
    model.setRowCount(weeks);
    
    int i = start_day - 1;
    for(int day = 1; day <= number_of_days; day++)
    {
        model.setValueAt(day, i/7 , i%7 ); 
        //setValueAt(Object aValue, int rowIndex, int columnIndex)
        //Sets the value in the cell at columnIndex and rowIndex to aValue.                            
         i = i + 1;
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingCalendar().setVisible(true);
                SwingCalendar sc = new SwingCalendar();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
